version: '3'
services:
  strapi:
    build: './app'
    environment:
      APP_KEYS: 'vCdhXHlys8woRDwnBwR5qQ==,OnxTpbuY/1VdvnAsG2JIHA==,TcqVxEUvNjtS30ndh4EN1Q==,PXhVM4CBZS6Z/uA85nlYkQ=='
      API_TOKEN_SALT: 'XUSyW4t6Wzg8TzUKWMFPKQ=='
      ADMIN_JWT_SECRET: 'GmziefmfmWtMTfM/F7g05A=='
      JWT_SECRET: 'jfDgNRoWhQDAEqcitxjw8Q=='
      NODE_ENV: 'development'
      DATABASE_HOST: 'movie-backend.csr0jb4deere.us-east-1.rds.amazonaws.com'
      DATABASE_PORT: '5432'
      DATABASE_NAME: 'movie_dev'
      DATABASE_USERNAME: 'michaelma'
      DATABASE_PASSWORD: 'footballwork'
      DATABASE_SSL: 'false'
    volumes:
      - ./app:/opt/app
    ports:
      - '1337:1337'
